# -*- coding: utf-8 -*-
"""AtividadeAvaliativa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-uiUIfewnUF1jiaTA9t0woGa14EFNzr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("/content/202301_NFe_NotaFiscalItem.csv", encoding='ISO-8859-1', sep = ";")

df1 = pd.DataFrame(data)

df1.columns # mostrando as colunas

df1.tail(10)

df1.isnull().sum() # sabendo se há valores nulos

df1.info() # para ver a quantidade de colunas

Estados_Destinatirio = df1['UF DESTINATÁRIO'].value_counts()
Estados_Destinatirio

df1['NÚMERO'].value_counts()

df1[df1['NÚMERO'] == 16]

contagem_de_16 = (df1['NÚMERO'] == 16).sum()
contagem_de_16

df1.drop(["CPF/CNPJ Emitente", "CNPJ DESTINATÁRIO", "INDICADOR IE DESTINATÁRIO", "CFOP", "NCM/SH (TIPO DE PRODUTO)", "CÓDIGO NCM/SH"] , axis=1, inplace=True)
 # exluindo colunas

df1.columns

df1["CONSUMIDOR FINAL"].unique()
# O Consumidor Final, pode ser uma Pessoa Física ou
# Pessoa Jurídica, apresentada como Destinatária da NF-e ou NFC-e, que está adquirindo
# um produto / mercadoria para seu uso, normalmente, produtos em seu estado final de comercialização,
# como um celular, um notebook, uma mesa, cadeira, televisão, etc.
# Já o Consumidor Normal, que também pode ser Pessoa Física ou Pessoa Jurídica,
# é um tipo de identificação permitida apenas para NF-e, e que normalmente o
# Destinatário é informado como Contribuinte de ICMS. Nessa operação, o produto
# / mercadoria comercializada, está sendo adquirida para compor a fabricação de um
# novo produto, para ser modificada, ou revendida. Nesse caso, o Destinatário dessa NF-e
# não é Consumidor Final porque ele não o está comprando para uso próprio, mas sim
# para tratá-lo e vendê-lo a outra Pessoa.

